version: '3.3'

services:
  api_gateway:
    build: ./back_end/api_gateway
    container_name: api_gateway
    ports:
      - "8000:8000"
    volumes:
      - ./back_end/api_gateway:/app
    depends_on:
      - consul
    environment:
      - DJANGO_SETTINGS_MODULE=gateway.settings
    command: gunicorn --bind 0.0.0.0:8000 gateway.wsgi:application

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api_gateway
      - consul
      - frontend

  consul:
    image: hashicorp/consul:1.15.2
    container_name: consul
    ports:
      - "8500:8500"
      - "8600:8600/udp"
    volumes:
      - ./consul/api_gateway.json:/consul/config/api_gateway.json

  frontend:
    build: ./front_end/app
    container_name: frontend
    ports:
      - "3000:3000"
    volumes:
      - ./front_end/app:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm start


  db:
    image: nouchka/sqlite3:latest
    container_name: sqlite
    volumes:
      - ./back_end/db.sqlite3:/data/db.sqlite3
