name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest

    services:
      consul:
        image: hashicorp/consul:latest
        ports:
          - 8500:8500

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # Node.js (Frontend Build)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.13.1'
      - name: Install Dependencies and Build Frontend
        working-directory: front_end/app
        run: |
          npm install
          npm run build

      # Backend Setup (API Gateway and Python Service)
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.3'
      
      # Install Backend Dependencies for API Gateway
      - name: Install Backend Dependencies for API Gateway
        working-directory: back_end/auth_service
        run: |
          python -m venv venv
          . venv/bin/activate
          pip install -r requirements.txt

      # Install Backend Dependencies for Python Service
      - name: Install Backend Dependencies for Python Service
        working-directory: back_end/file_service
        run: |
          python -m venv venv
          . venv/bin/activate
          pip install -r requirements.txt

      # Run Django Tests (Uncomment when tests are written)
      # - name: Run Django Tests
      #   working-directory: ./back_end/file_service
      #   run: |
      #     . venv/bin/activate
      #     python manage.py test

      # Nginx Validation (Optional)
      - name: Install Nginx
        run: sudo apt-get install -y nginx
        
      - name: Validate Nginx Configuration
        run: sudo nginx -t
